language:
  - node_js
node_js:
  - "8.9.0"
  - "9"
  - "node"
notifications:
  - email: false
before_install:
- npm install -g codecov
after_success:
  - codecov --file coverage/lcov.info --disable search